name: unit-tests

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/requirements.txt
          pip install -U pip setuptools wheel ruamel.yaml.clib
      - name: Test with pytest
        run: LANG=en_US.UTF-8 pytest
